using System.Reflection;
using System.Text;

namespace QwenCode.IpcGen;

internal sealed class TypeScriptEmitter
{
    private readonly Dictionary<Type, string> _definitions = [];
    private readonly HashSet<Type> _visited = [];
    private readonly NullabilityInfoContext _nullabilityContext = new();

    public string Emit(IReadOnlyCollection<IpcMethod> methods)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* Auto-generated by QwenCode.IpcGen. */");
        sb.AppendLine("/* eslint-disable @typescript-eslint/no-explicit-any */");
        sb.AppendLine();

        foreach (var method in methods)
        {
            if (method.InputType is not null)
            {
                _ = Map(method.InputType, method.InputNullability);
            }

            if (method.OutputType != typeof(void))
            {
                _ = Map(method.OutputType, method.OutputNullability);
            }
        }

        foreach (var definition in _definitions.OrderBy(item => item.Key.Name))
        {
            sb.AppendLine(definition.Value);
            sb.AppendLine();
        }

        sb.AppendLine("export interface QwenDesktopBridge {");
        foreach (var method in methods.OrderBy(item => item.Channel))
        {
            sb.AppendLine($"  {EmitMethodSignature(method)}");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("export const qwenDesktopChannels = {");
        foreach (var method in methods.OrderBy(item => item.Channel))
        {
            sb.AppendLine($"  {method.MethodName}: '{method.Channel}',");
        }
        sb.AppendLine("} as const");

        return sb.ToString();
    }

    private string EmitMethodSignature(IpcMethod method)
    {
        var input = method.InputType is null
            ? string.Empty
            : $"request: {Map(method.InputType, method.InputNullability)}";

        return method.Kind switch
        {
            IpcKind.Invoke => $"{method.MethodName}({input}): Promise<{Map(method.OutputType, method.OutputNullability)}>;",
            IpcKind.Send => $"{method.MethodName}({input}): void;",
            IpcKind.Event => $"{method.MethodName}(callback: (payload: {Map(method.OutputType, method.OutputNullability)}) => void): () => void;",
            _ => throw new ArgumentOutOfRangeException()
        };
    }

    private string Map(Type type, NullabilityInfo? nullability = null)
    {
        var nullable = Nullable.GetUnderlyingType(type);
        if (nullable is not null)
        {
            return $"{Map(nullable, nullability)} | null";
        }

        if (type == typeof(void))
        {
            return "void";
        }

        if (type == typeof(string))
        {
            return ApplyNullability("string", type, nullability);
        }

        if (type == typeof(Guid))
        {
            return "string";
        }

        if (type == typeof(Uri))
        {
            return ApplyNullability("string", type, nullability);
        }

        if (type == typeof(bool))
        {
            return "boolean";
        }

        if (type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(DateOnly) || type == typeof(TimeOnly))
        {
            return "string";
        }

        if (type.IsPrimitive || type == typeof(decimal))
        {
            return "number";
        }

        if (type.IsArray)
        {
            return $"{Map(type.GetElementType()!, nullability?.ElementType)}[]";
        }

        if (TryMapDictionary(type, nullability, out var dictionaryType))
        {
            return dictionaryType;
        }

        if (TryMapEnumerable(type, nullability, out var enumerableType))
        {
            return enumerableType;
        }

        if (type.IsEnum)
        {
            EnsureEnum(type);
            return type.Name;
        }

        if (ShouldEmitStructuredType(type))
        {
            EnsureInterface(type);
            return ApplyNullability(type.Name, type, nullability);
        }

        return ApplyNullability("unknown", type, nullability);
    }

    private bool TryMapEnumerable(Type type, NullabilityInfo? nullability, out string result)
    {
        var candidate = type.GetInterfaces().Concat([type]).FirstOrDefault(item =>
            item.IsGenericType &&
            item.GetGenericTypeDefinition() == typeof(IEnumerable<>));

        if (candidate is not null)
        {
            var elementType = candidate.GetGenericArguments()[0];
            var elementNullability = nullability?.GenericTypeArguments.FirstOrDefault();
            result = $"{Map(elementType, elementNullability)}[]";
            return true;
        }

        result = string.Empty;
        return false;
    }

    private bool TryMapDictionary(Type type, NullabilityInfo? nullability, out string result)
    {
        var candidate = type.GetInterfaces().Concat([type]).FirstOrDefault(item =>
            item.IsGenericType &&
            item.GetGenericTypeDefinition() == typeof(IReadOnlyDictionary<,>) &&
            item.GetGenericArguments()[0] == typeof(string));

        if (candidate is not null)
        {
            var valueNullability = nullability?.GenericTypeArguments.Skip(1).FirstOrDefault();
            result = $"Record<string, {Map(candidate.GetGenericArguments()[1], valueNullability)}>";
            return true;
        }

        candidate = type.GetInterfaces().Concat([type]).FirstOrDefault(item =>
            item.IsGenericType &&
            item.GetGenericTypeDefinition() == typeof(Dictionary<,>) &&
            item.GetGenericArguments()[0] == typeof(string));

        if (candidate is not null)
        {
            var valueNullability = nullability?.GenericTypeArguments.Skip(1).FirstOrDefault();
            result = $"Record<string, {Map(candidate.GetGenericArguments()[1], valueNullability)}>";
            return true;
        }

        result = string.Empty;
        return false;
    }

    private void EnsureEnum(Type type)
    {
        if (_visited.Add(type) == false)
        {
            return;
        }

        var values = Enum.GetNames(type)
            .Select(name => $"'{char.ToLowerInvariant(name[0])}{name[1..]}'");

        _definitions[type] = $"export type {type.Name} = {string.Join(" | ", values)};";
    }

    private void EnsureInterface(Type type)
    {
        if (_visited.Add(type) == false)
        {
            return;
        }

        var lines = new List<string> { $"export interface {type.Name} {{" };
        foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            var name = ToCamelCase(property.Name);
            lines.Add($"  {name}: {Map(property.PropertyType, _nullabilityContext.Create(property))};");
        }
        lines.Add("}");

        _definitions[type] = string.Join(Environment.NewLine, lines);
    }

    private static string ApplyNullability(string mappedType, Type type, NullabilityInfo? nullability)
    {
        if (type.IsValueType || mappedType.EndsWith(" | null", StringComparison.Ordinal))
        {
            return mappedType;
        }

        return nullability?.ReadState == NullabilityState.Nullable
            ? $"{mappedType} | null"
            : mappedType;
    }

    private static bool ShouldEmitStructuredType(Type type)
    {
        var ns = type.Namespace;
        if (string.IsNullOrWhiteSpace(ns))
        {
            return false;
        }

        return ns.StartsWith("QwenCode.App", StringComparison.Ordinal) ||
               ns.StartsWith("QwenCode.Core.Models", StringComparison.Ordinal) ||
               ns.StartsWith("QwenCode.Core.Runtime", StringComparison.Ordinal);
    }

    private static string ToCamelCase(string value)
        => string.IsNullOrEmpty(value)
            ? value
            : string.Create(value.Length, value, static (span, source) =>
            {
                span[0] = char.ToLowerInvariant(source[0]);
                source.AsSpan(1).CopyTo(span[1..]);
            });
}
