using System.Reflection;
using System.Text;

namespace QwenCode.IpcGen;

internal sealed class TypeScriptEmitter
{
    private readonly Dictionary<Type, string> _definitions = [];
    private readonly HashSet<Type> _visited = [];

    public string Emit(IReadOnlyCollection<IpcMethod> methods)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* Auto-generated by QwenCode.IpcGen. */");
        sb.AppendLine("/* eslint-disable @typescript-eslint/no-explicit-any */");
        sb.AppendLine();

        foreach (var method in methods)
        {
            if (method.InputType is not null)
            {
                _ = Map(method.InputType);
            }

            if (method.OutputType != typeof(void))
            {
                _ = Map(method.OutputType);
            }
        }

        foreach (var definition in _definitions.OrderBy(item => item.Key.Name))
        {
            sb.AppendLine(definition.Value);
            sb.AppendLine();
        }

        sb.AppendLine("export interface QwenDesktopBridge {");
        foreach (var method in methods.OrderBy(item => item.Channel))
        {
            sb.AppendLine($"  {EmitMethodSignature(method)}");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("export const qwenDesktopChannels = {");
        foreach (var method in methods.OrderBy(item => item.Channel))
        {
            sb.AppendLine($"  {method.MethodName}: '{method.Channel}',");
        }
        sb.AppendLine("} as const");

        return sb.ToString();
    }

    private string EmitMethodSignature(IpcMethod method)
    {
        var input = method.InputType is null
            ? string.Empty
            : $"request: {Map(method.InputType)}";

        return method.Kind switch
        {
            IpcKind.Invoke => $"{method.MethodName}({input}): Promise<{Map(method.OutputType)}>;",
            IpcKind.Send => $"{method.MethodName}({input}): void;",
            IpcKind.Event => $"{method.MethodName}(callback: (payload: {Map(method.OutputType)}) => void): () => void;",
            _ => throw new ArgumentOutOfRangeException()
        };
    }

    private string Map(Type type)
    {
        var nullable = Nullable.GetUnderlyingType(type);
        if (nullable is not null)
        {
            return $"{Map(nullable)} | null";
        }

        if (type == typeof(void))
        {
            return "void";
        }

        if (type == typeof(string) || type == typeof(Guid) || type == typeof(Uri))
        {
            return "string";
        }

        if (type == typeof(bool))
        {
            return "boolean";
        }

        if (type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(DateOnly) || type == typeof(TimeOnly))
        {
            return "string";
        }

        if (type.IsPrimitive || type == typeof(decimal))
        {
            return "number";
        }

        if (type.IsArray)
        {
            return $"{Map(type.GetElementType()!)}[]";
        }

        if (TryMapEnumerable(type, out var enumerableType))
        {
            return enumerableType;
        }

        if (TryMapDictionary(type, out var dictionaryType))
        {
            return dictionaryType;
        }

        if (type.IsEnum)
        {
            EnsureEnum(type);
            return type.Name;
        }

        if (type.Namespace?.StartsWith("QwenCode.App", StringComparison.Ordinal) == true)
        {
            EnsureInterface(type);
            return type.Name;
        }

        return "unknown";
    }

    private bool TryMapEnumerable(Type type, out string result)
    {
        var enumerable = type.IsGenericType &&
                         type.GetGenericArguments().Length == 1 &&
                         type.GetInterfaces().Concat([type]).Any(candidate =>
                             candidate.IsGenericType &&
                             candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>));

        if (enumerable)
        {
            result = $"{Map(type.GetGenericArguments()[0])}[]";
            return true;
        }

        result = string.Empty;
        return false;
    }

    private bool TryMapDictionary(Type type, out string result)
    {
        var candidate = type.GetInterfaces().Concat([type]).FirstOrDefault(item =>
            item.IsGenericType &&
            item.GetGenericTypeDefinition() == typeof(IReadOnlyDictionary<,>) &&
            item.GetGenericArguments()[0] == typeof(string));

        if (candidate is not null)
        {
            result = $"Record<string, {Map(candidate.GetGenericArguments()[1])}>";
            return true;
        }

        candidate = type.GetInterfaces().Concat([type]).FirstOrDefault(item =>
            item.IsGenericType &&
            item.GetGenericTypeDefinition() == typeof(Dictionary<,>) &&
            item.GetGenericArguments()[0] == typeof(string));

        if (candidate is not null)
        {
            result = $"Record<string, {Map(candidate.GetGenericArguments()[1])}>";
            return true;
        }

        result = string.Empty;
        return false;
    }

    private void EnsureEnum(Type type)
    {
        if (_visited.Add(type) == false)
        {
            return;
        }

        var values = Enum.GetNames(type)
            .Select(name => $"'{char.ToLowerInvariant(name[0])}{name[1..]}'");

        _definitions[type] = $"export type {type.Name} = {string.Join(" | ", values)};";
    }

    private void EnsureInterface(Type type)
    {
        if (_visited.Add(type) == false)
        {
            return;
        }

        var lines = new List<string> { $"export interface {type.Name} {{" };
        foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            var name = ToCamelCase(property.Name);
            lines.Add($"  {name}: {Map(property.PropertyType)};");
        }
        lines.Add("}");

        _definitions[type] = string.Join(Environment.NewLine, lines);
    }

    private static string ToCamelCase(string value)
        => string.IsNullOrEmpty(value)
            ? value
            : string.Create(value.Length, value, static (span, source) =>
            {
                span[0] = char.ToLowerInvariant(source[0]);
                source.AsSpan(1).CopyTo(span[1..]);
            });
}
