/* Auto-generated by QwenCode.IpcGen. */
/* eslint-disable @typescript-eslint/no-explicit-any */

export interface AppBootstrapPayload {
  productName: string;
  currentMode: DesktopMode;
  currentLocale: string;
  locales: LocaleOption[];
  sources: SourceMirrorPaths;
  tracks: ResearchTrack[];
  compatibilityGoals: string[];
}

export type DesktopMode = 'chat' | 'code';

export interface DesktopStateChangedEvent {
  currentMode: DesktopMode;
  currentLocale: string;
  timestampUtc: string;
}

export interface LocaleOption {
  code: string;
  name: string;
  nativeName: string;
}

export interface ResearchTrack {
  title: string;
  summary: string;
}

export interface SetLocaleRequest {
  locale: string;
}

export interface SetModeRequest {
  mode: DesktopMode;
}

export interface SourceMirrorPaths {
  workspaceRoot: string;
  qwenRoot: string;
  claudeRoot: string;
  ipcReferenceRoot: string;
}

export interface QwenDesktopBridge {
  bootstrap(): Promise<AppBootstrapPayload>;
  setLocale(request: SetLocaleRequest): Promise<DesktopStateChangedEvent>;
  setMode(request: SetModeRequest): Promise<DesktopStateChangedEvent>;
  subscribeStateChanged(callback: (payload: DesktopStateChangedEvent) => void): () => void;
}

export const qwenDesktopChannels = {
  bootstrap: 'qwen-desktop:app:bootstrap',
  setLocale: 'qwen-desktop:app:set-locale',
  setMode: 'qwen-desktop:app:set-mode',
  subscribeStateChanged: 'qwen-desktop:app:state-changed',
} as const
