/* Auto-generated by QwenCode.IpcGen. */
/* eslint-disable @typescript-eslint/no-explicit-any */

export interface ActiveTurnState {
  sessionId: string;
  prompt: string;
  transcriptPath: string;
  workingDirectory: string;
  gitBranch: string;
  toolName: string;
  stage: string;
  status: string;
  contentSnapshot: string;
  startedAtUtc: string;
  lastUpdatedAtUtc: string;
}

export interface AdoptionPattern {
  area: string;
  qwenSource: string;
  claudeReference: string;
  desktopDirection: string;
  deliveryState: string;
}

export interface AnswerDesktopSessionQuestionRequest {
  sessionId: string;
  entryId: string;
  answers: DesktopQuestionAnswer[];
}

export interface AppBootstrapPayload {
  productName: string;
  currentMode: DesktopMode;
  currentLocale: string;
  locales: LocaleOption[];
  workspaceRoot: string;
  tracks: ResearchTrack[];
  compatibilityGoals: string[];
  capabilityLanes: CapabilityLane[];
  adoptionPatterns: AdoptionPattern[];
  recentSessions: SessionPreview[];
  activeTurns: ActiveTurnState[];
  recoverableTurns: RecoverableTurnState[];
  projectSummary: ProjectSummarySnapshot;
  qwenCompatibility: QwenCompatibilitySnapshot;
  qwenRuntime: QwenRuntimeProfile;
  qwenTools: ToolCatalogSnapshot;
  qwenNativeHost: NativeToolHostSnapshot;
  qwenAuth: AuthStatusSnapshot;
  qwenMcp: McpSnapshot;
  qwenExtensions: ExtensionSnapshot;
  qwenChannels: ChannelSnapshot;
  qwenWorkspace: WorkspaceSnapshot;
}

export interface ApprovalProfile {
  defaultMode: string;
  confirmShellCommands: boolean | null;
  confirmFileEdits: boolean | null;
  allowRules: string[];
  askRules: string[];
  denyRules: string[];
}

export interface ApproveChannelPairingRequest {
  name: string;
  code: string;
}

export interface ApproveDesktopSessionToolRequest {
  sessionId: string;
  entryId: string;
}

export interface AuthStatusSnapshot {
  selectedType: string;
  selectedScope: string;
  displayName: string;
  status: string;
  model: string;
  endpoint: string;
  apiKeyEnvironmentVariable: string;
  hasApiKey: boolean;
  hasQwenOAuthCredentials: boolean;
  hasRefreshToken: boolean;
  credentialPath: string;
  lastError: string;
  lastAuthenticatedAtUtc: string | null;
  deviceFlow: QwenOAuthDeviceFlowSnapshot;
}

export interface CancelDesktopSessionTurnRequest {
  sessionId: string;
}

export interface CancelDesktopSessionTurnResult {
  sessionId: string;
  cancelled: boolean;
  message: string;
  timestampUtc: string;
}

export interface CancelQwenOAuthDeviceFlowRequest {
  flowId: string;
}

export interface CapabilityLane {
  title: string;
  summary: string;
  responsibilities: string[];
}

export interface ChannelDefinition {
  name: string;
  type: string;
  scope: string;
  description: string;
  senderPolicy: string;
  sessionScope: string;
  workingDirectory: string;
  approvalMode: string;
  model: string;
  status: string;
  supportsPairing: boolean;
  sessionCount: number;
  pendingPairingCount: number;
  allowlistCount: number;
}

export interface ChannelPairingRequest {
  senderId: string;
  senderName: string;
  code: string;
  createdAtUtc: string;
  minutesAgo: number;
}

export interface ChannelPairingSnapshot {
  channelName: string;
  pendingCount: number;
  allowlistCount: number;
  pendingRequests: ChannelPairingRequest[];
}

export interface ChannelSnapshot {
  isServiceRunning: boolean;
  serviceProcessId: number | null;
  serviceStartedAtUtc: string;
  serviceUptimeText: string;
  supportedTypes: string[];
  channels: ChannelDefinition[];
}

export interface CleanupManagedWorktreeSessionRequest {
  sessionId: string;
}

export interface ConfigureCodingPlanAuthRequest {
  scope: string;
  region: string;
  apiKey: string;
  model: string;
}

export interface ConfigureOpenAiCompatibleAuthRequest {
  scope: string;
  authType: string;
  model: string;
  baseUrl: string;
  apiKey: string;
  apiKeyEnvironmentVariable: string;
}

export interface ConfigureQwenOAuthRequest {
  scope: string;
  accessToken: string;
  refreshToken: string;
  tokenType: string;
  resourceUrl: string;
  idToken: string;
  expiresAtUtc: string | null;
}

export interface CreateManagedWorktreeRequest {
  sessionId: string;
  name: string;
  baseBranch: string;
}

export type DesktopMode = 'code';

export interface DesktopQuestionAnswer {
  questionIndex: number;
  value: string;
}

export interface DesktopQuestionOption {
  label: string;
  description: string;
}

export interface DesktopQuestionPrompt {
  header: string;
  question: string;
  multiSelect: boolean;
  options: DesktopQuestionOption[];
}

export interface DesktopSessionActivitySummary {
  userCount: number;
  assistantCount: number;
  commandCount: number;
  toolCount: number;
  pendingApprovalCount: number;
  pendingQuestionCount: number;
  completedToolCount: number;
  failedToolCount: number;
  lastTimestamp: string;
}

export interface DesktopSessionDetail {
  session: SessionPreview;
  transcriptPath: string;
  entryCount: number;
  windowOffset: number;
  windowSize: number;
  hasOlderEntries: boolean;
  hasNewerEntries: boolean;
  summary: DesktopSessionActivitySummary;
  entries: DesktopSessionEntry[];
}

export interface DesktopSessionEntry {
  id: string;
  type: string;
  timestamp: string;
  workingDirectory: string;
  gitBranch: string;
  title: string;
  body: string;
  status: string;
  toolName: string;
  approvalState: string;
  exitCode: number | null;
  arguments: string;
  scope: string;
  sourcePath: string;
  resolutionStatus: string;
  resolvedAt: string;
  changedFiles: string[];
  questions: DesktopQuestionPrompt[];
  answers: DesktopQuestionAnswer[];
}

export interface DesktopSessionEvent {
  sessionId: string;
  kind: DesktopSessionEventKind;
  timestampUtc: string;
  message: string;
  workingDirectory: string;
  gitBranch: string;
  commandName: string;
  toolName: string;
  status: string;
  contentDelta: string;
  contentSnapshot: string;
  agentName: string;
}

export type DesktopSessionEventKind = 'turnStarted' | 'commandCompleted' | 'toolApprovalRequired' | 'userInputRequired' | 'toolCompleted' | 'toolBlocked' | 'toolFailed' | 'toolApproved' | 'userInputReceived' | 'assistantPreparingContext' | 'assistantGenerating' | 'assistantStreaming' | 'assistantCompleted' | 'turnInterrupted' | 'turnReattached' | 'turnCancelled' | 'turnCompleted';

export interface DesktopSessionTurnResult {
  session: SessionPreview;
  assistantSummary: string;
  createdNewSession: boolean;
  toolExecution: NativeToolExecutionResult;
  resolvedCommand: ResolvedCommand;
}

export interface DesktopStateChangedEvent {
  currentMode: DesktopMode;
  currentLocale: string;
  timestampUtc: string;
}

export interface DisconnectAuthRequest {
  scope: string;
  clearPersistedCredentials: boolean;
}

export interface DismissInterruptedTurnRequest {
  sessionId: string;
}

export interface DismissInterruptedTurnResult {
  sessionId: string;
  dismissed: boolean;
  message: string;
  timestampUtc: string;
}

export interface ExecuteNativeToolRequest {
  toolName: string;
  argumentsJson: string;
  approveExecution: boolean;
}

export interface ExtensionDefinition {
  name: string;
  version: string;
  path: string;
  wrapperPath: string;
  status: string;
  installType: string;
  source: string;
  userEnabled: boolean;
  workspaceEnabled: boolean;
  isActive: boolean;
  description: string;
  contextFiles: string[];
  commands: string[];
  skills: string[];
  agents: string[];
  mcpServers: string[];
  channels: string[];
  settingsCount: number;
  hookEventCount: number;
  lastError: string;
}

export interface ExtensionSettingsSnapshot {
  extensionName: string;
  version: string;
  installType: string;
  path: string;
  settings: ExtensionSettingValue[];
}

export interface ExtensionSettingValue {
  name: string;
  description: string;
  environmentVariable: string;
  sensitive: boolean;
  userValue: string;
  workspaceValue: string;
  effectiveValue: string;
  hasUserValue: boolean;
  hasWorkspaceValue: boolean;
}

export interface ExtensionSnapshot {
  totalCount: number;
  activeCount: number;
  linkedCount: number;
  missingCount: number;
  extensions: ExtensionDefinition[];
}

export interface FileDiscoverySnapshot {
  gitAware: boolean;
  hasQwenIgnore: boolean;
  candidateFileCount: number;
  visibleFileCount: number;
  gitIgnoredCount: number;
  qwenIgnoredCount: number;
  qwenIgnorePatternCount: number;
  contextFiles: string[];
  sampleVisibleFiles: string[];
  sampleGitIgnoredFiles: string[];
  sampleQwenIgnoredFiles: string[];
}

export interface GetChannelPairingRequest {
  name: string;
}

export interface GetDesktopSessionRequest {
  sessionId: string;
  offset: number | null;
  limit: number | null;
}

export interface GetExtensionSettingsRequest {
  name: string;
}

export interface GitRepositorySnapshot {
  isGitAvailable: boolean;
  isRepository: boolean;
  worktreeSupported: boolean;
  repositoryRoot: string;
  currentBranch: string;
  currentCommit: string;
  gitVersion: string;
  managedSessionCount: number;
  managedWorktreesRoot: string;
  worktrees: GitWorktreeEntry[];
}

export interface GitWorktreeEntry {
  path: string;
  branch: string;
  head: string;
  name: string;
  sessionId: string;
  isCurrent: boolean;
  isManaged: boolean;
}

export interface InstallExtensionRequest {
  sourcePath: string;
  installMode: string;
}

export interface LocaleOption {
  code: string;
  name: string;
  nativeName: string;
}

export interface McpServerDefinition {
  name: string;
  scope: string;
  transport: string;
  commandOrUrl: string;
  arguments: string[];
  environmentVariables: Record<string, string>;
  headers: Record<string, string>;
  timeoutMs: number | null;
  trust: boolean;
  description: string;
  includeTools: string[];
  excludeTools: string[];
  settingsPath: string;
  status: string;
  lastReconnectAttemptUtc: string | null;
  lastError: string;
  hasPersistedToken: boolean;
  discoveredToolsCount: number;
  discoveredPromptsCount: number;
  supportsPrompts: boolean;
  supportsResources: boolean;
  lastDiscoveryUtc: string | null;
}

export interface McpServerRegistrationRequest {
  name: string;
  scope: string;
  transport: string;
  commandOrUrl: string;
  arguments: string[];
  environmentVariables: Record<string, string>;
  headers: Record<string, string>;
  timeoutMs: number | null;
  trust: boolean;
  description: string;
  includeTools: string[];
  excludeTools: string[];
}

export interface McpSnapshot {
  totalCount: number;
  connectedCount: number;
  disconnectedCount: number;
  missingCount: number;
  tokenCount: number;
  servers: McpServerDefinition[];
}

export interface NativeToolExecutionResult {
  toolName: string;
  status: string;
  approvalState: string;
  workingDirectory: string;
  output: string;
  errorMessage: string;
  exitCode: number;
  changedFiles: string[];
  questions: DesktopQuestionPrompt[];
  answers: DesktopQuestionAnswer[];
}

export interface NativeToolHostSnapshot {
  registeredCount: number;
  implementedCount: number;
  readyCount: number;
  approvalRequiredCount: number;
  tools: NativeToolRegistration[];
}

export interface NativeToolRegistration {
  name: string;
  displayName: string;
  kind: string;
  isImplemented: boolean;
  approvalState: string;
  approvalReason: string;
}

export interface ProjectSummarySnapshot {
  hasHistory: boolean;
  filePath: string;
  content: string;
  timestampText: string;
  timeAgo: string;
  overallGoal: string;
  currentPlan: string;
  totalTasks: number;
  doneCount: number;
  inProgressCount: number;
  todoCount: number;
  pendingTasks: string[];
  timestampUtc: string;
}

export interface QwenCommandSurface {
  id: string;
  name: string;
  scope: string;
  path: string;
  description: string;
  group: string;
}

export interface QwenCompatibilityLayer {
  id: string;
  title: string;
  scope: string;
  priority: number;
  path: string;
  exists: boolean;
  categories: string[];
}

export interface QwenCompatibilitySnapshot {
  projectRoot: string;
  defaultContextFileName: string;
  settingsLayers: QwenCompatibilityLayer[];
  surfaceDirectories: QwenSurfaceDirectory[];
  commands: QwenCommandSurface[];
  skills: QwenSkillSurface[];
}

export interface QwenOAuthDeviceFlowSnapshot {
  flowId: string;
  scope: string;
  status: string;
  verificationUri: string;
  verificationUriComplete: string;
  userCode: string;
  pollIntervalMs: number;
  browserLaunchAttempted: boolean;
  browserLaunchSucceeded: boolean;
  startedAtUtc: string;
  expiresAtUtc: string;
  completedAtUtc: string | null;
  errorMessage: string;
}

export interface QwenRuntimeProfile {
  projectRoot: string;
  globalQwenDirectory: string;
  runtimeBaseDirectory: string;
  runtimeSource: string;
  projectDataDirectory: string;
  chatsDirectory: string;
  historyDirectory: string;
  contextFileNames: string[];
  contextFilePaths: string[];
  folderTrustEnabled: boolean;
  isWorkspaceTrusted: boolean;
  workspaceTrustSource: string;
  approvalProfile: ApprovalProfile;
}

export interface QwenSkillSurface {
  id: string;
  name: string;
  scope: string;
  path: string;
  description: string;
  allowedTools: string[];
}

export interface QwenSurfaceDirectory {
  id: string;
  title: string;
  path: string;
  exists: boolean;
  itemCount: number;
  summary: string;
}

export interface ReconnectMcpServerRequest {
  name: string;
}

export interface RecoverableTurnState {
  sessionId: string;
  prompt: string;
  workingDirectory: string;
  gitBranch: string;
  recoveryReason: string;
  lastUpdatedAtUtc: string;
  contentSnapshot: string;
  toolName: string;
}

export interface RemoveExtensionRequest {
  name: string;
}

export interface RemoveMcpServerRequest {
  name: string;
  scope: string;
}

export interface ResearchTrack {
  title: string;
  summary: string;
}

export interface ResolvedCommand {
  name: string;
  scope: string;
  sourcePath: string;
  description: string;
  arguments: string;
  resolvedPrompt: string;
}

export interface ResumeInterruptedTurnRequest {
  sessionId: string;
  recoveryNote: string;
}

export interface SessionPreview {
  sessionId: string;
  title: string;
  lastActivity: string;
  category: string;
  mode: DesktopMode;
  status: string;
  workingDirectory: string;
  gitBranch: string;
  messageCount: number;
  transcriptPath: string;
}

export interface SetExtensionEnabledRequest {
  name: string;
  scope: string;
  enabled: boolean;
}

export interface SetExtensionSettingValueRequest {
  name: string;
  setting: string;
  scope: string;
  value: string;
}

export interface SetLocaleRequest {
  locale: string;
}

export interface StartDesktopSessionTurnRequest {
  sessionId: string;
  prompt: string;
  workingDirectory: string;
  toolName: string;
  toolArgumentsJson: string;
  approveToolExecution: boolean;
}

export interface StartQwenOAuthDeviceFlowRequest {
  scope: string;
}

export interface ToolCatalogSnapshot {
  sourceMode: string;
  totalCount: number;
  allowedCount: number;
  askCount: number;
  denyCount: number;
  tools: ToolDescriptor[];
}

export interface ToolDescriptor {
  name: string;
  displayName: string;
  kind: string;
  sourcePath: string;
  approvalState: string;
  approvalReason: string;
}

export interface WorkspaceSnapshot {
  git: GitRepositorySnapshot;
  discovery: FileDiscoverySnapshot;
}

export interface QwenDesktopBridge {
  bootstrap(): Promise<AppBootstrapPayload>;
  setLocale(request: SetLocaleRequest): Promise<DesktopStateChangedEvent>;
  subscribeStateChanged(callback: (payload: DesktopStateChangedEvent) => void): () => void;
  cancelQwenOAuthDeviceFlow(request: CancelQwenOAuthDeviceFlowRequest): Promise<AuthStatusSnapshot>;
  subscribeAuthChanged(callback: (payload: AuthStatusSnapshot) => void): () => void;
  configureCodingPlanAuth(request: ConfigureCodingPlanAuthRequest): Promise<AuthStatusSnapshot>;
  configureOpenAiCompatibleAuth(request: ConfigureOpenAiCompatibleAuthRequest): Promise<AuthStatusSnapshot>;
  configureQwenOAuth(request: ConfigureQwenOAuthRequest): Promise<AuthStatusSnapshot>;
  disconnectAuth(request: DisconnectAuthRequest): Promise<AuthStatusSnapshot>;
  startQwenOAuthDeviceFlow(request: StartQwenOAuthDeviceFlowRequest): Promise<AuthStatusSnapshot>;
  getAuthStatus(): Promise<AuthStatusSnapshot>;
  approveChannelPairing(request: ApproveChannelPairingRequest): Promise<ChannelPairingSnapshot>;
  getChannelPairings(request: GetChannelPairingRequest): Promise<ChannelPairingSnapshot>;
  getExtensionSettings(request: GetExtensionSettingsRequest): Promise<ExtensionSettingsSnapshot>;
  installExtension(request: InstallExtensionRequest): Promise<ExtensionSnapshot>;
  removeExtension(request: RemoveExtensionRequest): Promise<ExtensionSnapshot>;
  setExtensionEnabled(request: SetExtensionEnabledRequest): Promise<ExtensionSnapshot>;
  setExtensionSetting(request: SetExtensionSettingValueRequest): Promise<ExtensionSettingsSnapshot>;
  addMcpServer(request: McpServerRegistrationRequest): Promise<McpSnapshot>;
  reconnectMcpServer(request: ReconnectMcpServerRequest): Promise<McpSnapshot>;
  removeMcpServer(request: RemoveMcpServerRequest): Promise<McpSnapshot>;
  answerPendingQuestion(request: AnswerDesktopSessionQuestionRequest): Promise<DesktopSessionTurnResult>;
  approvePendingTool(request: ApproveDesktopSessionToolRequest): Promise<DesktopSessionTurnResult>;
  cancelSessionTurn(request: CancelDesktopSessionTurnRequest): Promise<CancelDesktopSessionTurnResult>;
  dismissInterruptedTurn(request: DismissInterruptedTurnRequest): Promise<DismissInterruptedTurnResult>;
  subscribeSessionEvents(callback: (payload: DesktopSessionEvent) => void): () => void;
  getSession(request: GetDesktopSessionRequest): Promise<DesktopSessionDetail>;
  getActiveTurns(): Promise<ActiveTurnState[]>;
  resumeInterruptedTurn(request: ResumeInterruptedTurnRequest): Promise<DesktopSessionTurnResult>;
  startSessionTurn(request: StartDesktopSessionTurnRequest): Promise<DesktopSessionTurnResult>;
  executeNativeTool(request: ExecuteNativeToolRequest): Promise<NativeToolExecutionResult>;
  cleanupManagedSession(request: CleanupManagedWorktreeSessionRequest): Promise<WorkspaceSnapshot>;
  createManagedWorktree(request: CreateManagedWorktreeRequest): Promise<WorkspaceSnapshot>;
  getWorkspaceSnapshot(): Promise<WorkspaceSnapshot>;
}

export const qwenDesktopChannels = {
  bootstrap: 'qwen-desktop:app:bootstrap',
  setLocale: 'qwen-desktop:app:set-locale',
  subscribeStateChanged: 'qwen-desktop:app:state-changed',
  cancelQwenOAuthDeviceFlow: 'qwen-desktop:auth:cancel-qwen-oauth-device-flow',
  subscribeAuthChanged: 'qwen-desktop:auth:changed',
  configureCodingPlanAuth: 'qwen-desktop:auth:configure-coding-plan',
  configureOpenAiCompatibleAuth: 'qwen-desktop:auth:configure-openai-compatible',
  configureQwenOAuth: 'qwen-desktop:auth:configure-qwen-oauth',
  disconnectAuth: 'qwen-desktop:auth:disconnect',
  startQwenOAuthDeviceFlow: 'qwen-desktop:auth:start-qwen-oauth-device-flow',
  getAuthStatus: 'qwen-desktop:auth:status',
  approveChannelPairing: 'qwen-desktop:channels:approve-pairing',
  getChannelPairings: 'qwen-desktop:channels:get-pairings',
  getExtensionSettings: 'qwen-desktop:extensions:get-settings',
  installExtension: 'qwen-desktop:extensions:install',
  removeExtension: 'qwen-desktop:extensions:remove',
  setExtensionEnabled: 'qwen-desktop:extensions:set-enabled',
  setExtensionSetting: 'qwen-desktop:extensions:set-setting',
  addMcpServer: 'qwen-desktop:mcp:add',
  reconnectMcpServer: 'qwen-desktop:mcp:reconnect',
  removeMcpServer: 'qwen-desktop:mcp:remove',
  answerPendingQuestion: 'qwen-desktop:sessions:answer-question',
  approvePendingTool: 'qwen-desktop:sessions:approve-tool',
  cancelSessionTurn: 'qwen-desktop:sessions:cancel-turn',
  dismissInterruptedTurn: 'qwen-desktop:sessions:dismiss-interrupted',
  subscribeSessionEvents: 'qwen-desktop:sessions:event',
  getSession: 'qwen-desktop:sessions:get',
  getActiveTurns: 'qwen-desktop:sessions:get-active-turns',
  resumeInterruptedTurn: 'qwen-desktop:sessions:resume-interrupted',
  startSessionTurn: 'qwen-desktop:sessions:start-turn',
  executeNativeTool: 'qwen-desktop:tools:execute-native',
  cleanupManagedSession: 'qwen-desktop:workspace:cleanup-managed-session',
  createManagedWorktree: 'qwen-desktop:workspace:create-managed-worktree',
  getWorkspaceSnapshot: 'qwen-desktop:workspace:get',
} as const
