/* Auto-generated by QwenCode.IpcGen. */
/* eslint-disable @typescript-eslint/no-explicit-any */

export interface AdoptionPattern {
  area: string;
  qwenSource: string;
  claudeReference: string;
  desktopDirection: string;
  deliveryState: string;
}

export interface AppBootstrapPayload {
  productName: string;
  currentMode: DesktopMode;
  currentLocale: string;
  locales: LocaleOption[];
  sources: SourceMirrorPaths;
  tracks: ResearchTrack[];
  compatibilityGoals: string[];
  capabilityLanes: CapabilityLane[];
  adoptionPatterns: AdoptionPattern[];
  recentSessions: SessionPreview[];
  sourceStatuses: SourceMirrorStatus[];
  runtimePortPlan: RuntimePortWorkItem[];
  qwenCompatibility: QwenCompatibilitySnapshot;
  qwenRuntime: QwenRuntimeProfile;
  qwenTools: QwenToolCatalogSnapshot;
  qwenNativeHost: QwenNativeToolHostSnapshot;
}

export interface ApproveDesktopSessionToolRequest {
  sessionId: string;
  entryId: string;
}

export interface CapabilityLane {
  title: string;
  summary: string;
  responsibilities: string[];
}

export type DesktopMode = 'code';

export interface DesktopSessionActivitySummary {
  userCount: number;
  assistantCount: number;
  commandCount: number;
  toolCount: number;
  pendingApprovalCount: number;
  completedToolCount: number;
  failedToolCount: number;
  lastTimestamp: string;
}

export interface DesktopSessionDetail {
  session: SessionPreview;
  transcriptPath: string;
  entryCount: number;
  summary: DesktopSessionActivitySummary;
  entries: DesktopSessionEntry[];
}

export interface DesktopSessionEntry {
  id: string;
  type: string;
  timestamp: string;
  workingDirectory: string;
  gitBranch: string;
  title: string;
  body: string;
  status: string;
  toolName: string;
  approvalState: string;
  exitCode: number | null;
  arguments: string;
  scope: string;
  sourcePath: string;
  resolutionStatus: string;
  resolvedAt: string;
  changedFiles: string[];
}

export interface DesktopSessionTurnResult {
  session: SessionPreview;
  assistantSummary: string;
  createdNewSession: boolean;
  toolExecution: QwenNativeToolExecutionResult;
  resolvedCommand: QwenResolvedCommand;
}

export interface DesktopStateChangedEvent {
  currentMode: DesktopMode;
  currentLocale: string;
  timestampUtc: string;
}

export interface ExecuteNativeToolRequest {
  toolName: string;
  argumentsJson: string;
  approveExecution: boolean;
}

export interface GetDesktopSessionRequest {
  sessionId: string;
}

export interface LocaleOption {
  code: string;
  name: string;
  nativeName: string;
}

export interface QwenApprovalProfile {
  defaultMode: string;
  confirmShellCommands: boolean | null;
  confirmFileEdits: boolean | null;
  allowRules: string[];
  askRules: string[];
  denyRules: string[];
}

export interface QwenCommandSurface {
  id: string;
  name: string;
  scope: string;
  path: string;
  description: string;
  group: string;
}

export interface QwenCompatibilityLayer {
  id: string;
  title: string;
  scope: string;
  priority: number;
  path: string;
  exists: boolean;
  categories: string[];
}

export interface QwenCompatibilitySnapshot {
  projectRoot: string;
  defaultContextFileName: string;
  settingsLayers: QwenCompatibilityLayer[];
  surfaceDirectories: QwenSurfaceDirectory[];
  commands: QwenCommandSurface[];
  skills: QwenSkillSurface[];
}

export interface QwenNativeToolExecutionResult {
  toolName: string;
  status: string;
  approvalState: string;
  workingDirectory: string;
  output: string;
  errorMessage: string;
  exitCode: number;
  changedFiles: string[];
}

export interface QwenNativeToolHostSnapshot {
  registeredCount: number;
  implementedCount: number;
  readyCount: number;
  approvalRequiredCount: number;
  tools: QwenNativeToolRegistration[];
}

export interface QwenNativeToolRegistration {
  name: string;
  displayName: string;
  kind: string;
  isImplemented: boolean;
  approvalState: string;
  approvalReason: string;
}

export interface QwenResolvedCommand {
  name: string;
  scope: string;
  sourcePath: string;
  description: string;
  arguments: string;
  resolvedPrompt: string;
}

export interface QwenRuntimeProfile {
  projectRoot: string;
  globalQwenDirectory: string;
  runtimeBaseDirectory: string;
  runtimeSource: string;
  projectDataDirectory: string;
  chatsDirectory: string;
  historyDirectory: string;
  contextFileNames: string[];
  contextFilePaths: string[];
  approvalProfile: QwenApprovalProfile;
}

export interface QwenSkillSurface {
  id: string;
  name: string;
  scope: string;
  path: string;
  description: string;
  allowedTools: string[];
}

export interface QwenSurfaceDirectory {
  id: string;
  title: string;
  path: string;
  exists: boolean;
  itemCount: number;
  summary: string;
}

export interface QwenToolCatalogSnapshot {
  sourceMode: string;
  totalCount: number;
  allowedCount: number;
  askCount: number;
  denyCount: number;
  tools: QwenToolDescriptor[];
}

export interface QwenToolDescriptor {
  name: string;
  displayName: string;
  kind: string;
  sourcePath: string;
  approvalState: string;
  approvalReason: string;
}

export interface ResearchTrack {
  title: string;
  summary: string;
}

export interface RuntimePortWorkItem {
  id: string;
  title: string;
  sourceSystem: string;
  targetModule: string;
  stage: string;
  summary: string;
  compatibilityContract: string;
  evidencePaths: string[];
}

export interface SessionPreview {
  sessionId: string;
  title: string;
  lastActivity: string;
  category: string;
  mode: DesktopMode;
  status: string;
  workingDirectory: string;
  gitBranch: string;
  messageCount: number;
  transcriptPath: string;
}

export interface SetLocaleRequest {
  locale: string;
}

export interface SourceMirrorPaths {
  workspaceRoot: string;
  qwenRoot: string;
  claudeRoot: string;
  ipcReferenceRoot: string;
}

export interface SourceMirrorStatus {
  id: string;
  title: string;
  path: string;
  status: string;
  summary: string;
  exists: boolean;
  isGitRepository: boolean;
  primaryMarker: string;
  highlights: string[];
}

export interface StartDesktopSessionTurnRequest {
  sessionId: string;
  prompt: string;
  workingDirectory: string;
  toolName: string;
  toolArgumentsJson: string;
  approveToolExecution: boolean;
}

export interface QwenDesktopBridge {
  bootstrap(): Promise<AppBootstrapPayload>;
  setLocale(request: SetLocaleRequest): Promise<DesktopStateChangedEvent>;
  subscribeStateChanged(callback: (payload: DesktopStateChangedEvent) => void): () => void;
  approvePendingTool(request: ApproveDesktopSessionToolRequest): Promise<DesktopSessionTurnResult>;
  getSession(request: GetDesktopSessionRequest): Promise<DesktopSessionDetail>;
  startSessionTurn(request: StartDesktopSessionTurnRequest): Promise<DesktopSessionTurnResult>;
  executeNativeTool(request: ExecuteNativeToolRequest): Promise<QwenNativeToolExecutionResult>;
}

export const qwenDesktopChannels = {
  bootstrap: 'qwen-desktop:app:bootstrap',
  setLocale: 'qwen-desktop:app:set-locale',
  subscribeStateChanged: 'qwen-desktop:app:state-changed',
  approvePendingTool: 'qwen-desktop:sessions:approve-tool',
  getSession: 'qwen-desktop:sessions:get',
  startSessionTurn: 'qwen-desktop:sessions:start-turn',
  executeNativeTool: 'qwen-desktop:tools:execute-native',
} as const
