/* Auto-generated by QwenCode.IpcGen. */
/* eslint-disable @typescript-eslint/no-explicit-any */

export interface ActiveArenaSessionState {
  sessionId: string;
  task: string;
  taskId: string;
  status: string;
  workingDirectory: string;
  baseBranch: string;
  roundCount: number;
  selectedWinner: string;
  startedAtUtc: string;
  lastUpdatedAtUtc: string;
  stats: ArenaSessionStats;
  agents: ArenaAgentStatusFile[];
}

export interface ActiveTurnState {
  sessionId: string;
  prompt: string;
  transcriptPath: string;
  workingDirectory: string;
  gitBranch: string;
  toolName: string;
  stage: string;
  status: string;
  contentSnapshot: string;
  startedAtUtc: string;
  lastUpdatedAtUtc: string;
}

export interface AdoptionPattern {
  area: string;
  qwenSource: string;
  claudeReference: string;
  desktopDirection: string;
  deliveryState: string;
}

export interface AnswerDesktopSessionQuestionRequest {
  sessionId: string;
  entryId: string;
  answers: DesktopQuestionAnswer[];
}

export interface AnswerDirectConnectSessionQuestionRequest {
  directConnectSessionId: string;
  answer: AnswerDesktopSessionQuestionRequest;
}

export interface AppBootstrapPayload {
  productName: string;
  currentMode: DesktopMode;
  currentLocale: string;
  locales: LocaleOption[];
  workspaceRoot: string;
  tracks: ResearchTrack[];
  compatibilityGoals: string[];
  capabilityLanes: CapabilityLane[];
  adoptionPatterns: AdoptionPattern[];
  recentSessions: SessionPreview[];
  activeTurns: ActiveTurnState[];
  activeArenaSessions: ActiveArenaSessionState[];
  recoverableTurns: RecoverableTurnState[];
  projectSummary: ProjectSummarySnapshot;
  qwenCompatibility: QwenCompatibilitySnapshot;
  qwenRuntime: QwenRuntimeProfile;
  qwenModels: RuntimeModelSnapshot;
  qwenTools: ToolCatalogSnapshot;
  qwenNativeHost: NativeToolHostSnapshot;
  qwenAuth: AuthStatusSnapshot;
  qwenMcp: McpSnapshot;
  qwenExtensions: ExtensionSnapshot;
  qwenChannels: ChannelSnapshot;
  qwenWorkspace: WorkspaceSnapshot;
}

export interface ApprovalProfile {
  defaultMode: string;
  confirmShellCommands: boolean | null;
  confirmFileEdits: boolean | null;
  allowRules: string[];
  askRules: string[];
  denyRules: string[];
}

export interface ApproveChannelPairingRequest {
  name: string;
  code: string;
}

export interface ApproveDesktopSessionToolRequest {
  sessionId: string;
  entryId: string;
  decision: string;
  feedback: string;
}

export interface ApproveDirectConnectSessionToolRequest {
  directConnectSessionId: string;
  approval: ApproveDesktopSessionToolRequest;
}

export interface ArenaAgentStatusFile {
  agentId: string;
  agentName: string;
  status: string;
  model: string;
  worktreeName: string;
  worktreePath: string;
  branch: string;
  providerName: string;
  stopReason: string;
  stats: AssistantExecutionStats;
  currentActivity: string;
  finalSummary: string;
  error: string;
  updatedAtUtc: string;
}

export interface ArenaSessionEvent {
  sessionId: string;
  kind: ArenaSessionEventKind;
  taskId: string;
  status: string;
  message: string;
  agentName: string;
  roundCount: number;
  selectedWinner: string;
  stats: ArenaSessionStats;
  timestampUtc: string;
}

export type ArenaSessionEventKind = 'sessionStarted' | 'sessionUpdated' | 'agentStarted' | 'agentStatsUpdated' | 'agentCompleted' | 'agentFailed' | 'roundCompleted' | 'sessionCancelled' | 'sessionCompleted' | 'sessionFailed' | 'sessionRemoved';

export interface ArenaSessionStats {
  agentCount: number;
  completedAgentCount: number;
  failedAgentCount: number;
  roundCount: number;
  toolCallCount: number;
  successfulToolCallCount: number;
  failedToolCallCount: number;
  totalDurationMs: number;
}

export interface AssistantExecutionStats {
  roundCount: number;
  toolCallCount: number;
  successfulToolCallCount: number;
  failedToolCallCount: number;
  durationMs: number;
}

export interface AuthStatusSnapshot {
  selectedType: string;
  selectedScope: string;
  displayName: string;
  status: string;
  model: string;
  endpoint: string;
  apiKeyEnvironmentVariable: string;
  hasApiKey: boolean;
  hasQwenOAuthCredentials: boolean;
  hasRefreshToken: boolean;
  credentialPath: string;
  lastError: string;
  lastAuthenticatedAtUtc: string | null;
  deviceFlow: QwenOAuthDeviceFlowSnapshot | null;
}

export interface AvailableModel {
  id: string;
  authType: string;
  baseUrl: string;
  apiKeyEnvironmentVariable: string;
  source: string;
  contextWindowSize: number;
  maxOutputTokens: number;
  isDefaultModel: boolean;
  isEmbeddingModel: boolean;
  capabilities: RuntimeModelCapabilities;
}

export interface CancelArenaSessionRequest {
  sessionId: string;
}

export interface CancelArenaSessionResult {
  sessionId: string;
  wasCancelled: boolean;
  message: string;
}

export interface CancelDesktopSessionTurnRequest {
  sessionId: string;
}

export interface CancelDesktopSessionTurnResult {
  sessionId: string;
  cancelled: boolean;
  message: string;
  timestampUtc: string;
}

export interface CancelDirectConnectSessionTurnRequest {
  directConnectSessionId: string;
  turn: CancelDesktopSessionTurnRequest;
}

export interface CancelQwenOAuthDeviceFlowRequest {
  flowId: string;
}

export interface CapabilityLane {
  title: string;
  summary: string;
  responsibilities: string[];
}

export interface ChannelDefinition {
  name: string;
  type: string;
  scope: string;
  description: string;
  senderPolicy: string;
  sessionScope: string;
  workingDirectory: string;
  approvalMode: string;
  model: string;
  status: string;
  supportsPairing: boolean;
  sessionCount: number;
  pendingPairingCount: number;
  allowlistCount: number;
}

export interface ChannelPairingRequest {
  senderId: string;
  senderName: string;
  code: string;
  createdAtUtc: string;
  minutesAgo: number;
}

export interface ChannelPairingSnapshot {
  channelName: string;
  pendingCount: number;
  allowlistCount: number;
  pendingRequests: ChannelPairingRequest[];
}

export interface ChannelSnapshot {
  isServiceRunning: boolean;
  serviceProcessId: number | null;
  serviceStartedAtUtc: string;
  serviceUptimeText: string;
  supportedTypes: string[];
  channels: ChannelDefinition[];
}

export interface CleanupManagedWorktreeSessionRequest {
  sessionId: string;
}

export interface CloseDirectConnectSessionRequest {
  directConnectSessionId: string;
}

export interface ConfigureCodingPlanAuthRequest {
  scope: string;
  region: string;
  apiKey: string;
  model: string;
}

export interface ConfigureOpenAiCompatibleAuthRequest {
  scope: string;
  authType: string;
  model: string;
  baseUrl: string;
  apiKey: string;
  apiKeyEnvironmentVariable: string;
}

export interface ConfigureQwenOAuthRequest {
  scope: string;
  accessToken: string;
  refreshToken: string;
  tokenType: string;
  resourceUrl: string;
  idToken: string;
  expiresAtUtc: string | null;
}

export interface CreateDirectConnectSessionRequest {
  preferredSessionId: string;
  workingDirectory: string;
}

export interface CreateExtensionScaffoldRequest {
  targetPath: string;
  template: string;
}

export interface CreateGitCheckpointRequest {
  message: string;
}

export interface CreateManagedWorktreeRequest {
  sessionId: string;
  name: string;
  baseBranch: string;
}

export type DesktopMode = 'code';

export interface DesktopQuestionAnswer {
  questionIndex: number;
  value: string;
}

export interface DesktopQuestionOption {
  label: string;
  description: string;
}

export interface DesktopQuestionPrompt {
  header: string;
  question: string;
  multiSelect: boolean;
  options: DesktopQuestionOption[];
}

export interface DesktopSessionActivitySummary {
  userCount: number;
  assistantCount: number;
  commandCount: number;
  toolCount: number;
  pendingApprovalCount: number;
  pendingQuestionCount: number;
  completedToolCount: number;
  failedToolCount: number;
  lastTimestamp: string;
}

export interface DesktopSessionDetail {
  session: SessionPreview;
  transcriptPath: string;
  entryCount: number;
  windowOffset: number;
  windowSize: number;
  hasOlderEntries: boolean;
  hasNewerEntries: boolean;
  summary: DesktopSessionActivitySummary;
  entries: DesktopSessionEntry[];
}

export interface DesktopSessionEntry {
  id: string;
  type: string;
  timestamp: string;
  workingDirectory: string;
  gitBranch: string;
  title: string;
  body: string;
  status: string;
  toolName: string;
  approvalState: string;
  exitCode: number | null;
  arguments: string;
  scope: string;
  sourcePath: string;
  resolutionStatus: string;
  resolvedAt: string;
  thinkingBody: string;
  thinkingDurationMs: number;
  changedFiles: string[];
  questions: DesktopQuestionPrompt[];
  answers: DesktopQuestionAnswer[];
}

export interface DesktopSessionEvent {
  sessionId: string;
  kind: DesktopSessionEventKind;
  timestampUtc: string;
  message: string;
  workingDirectory: string;
  gitBranch: string;
  commandName: string;
  toolName: string;
  toolCallId: string;
  toolCallGroupId: string;
  toolArgumentsJson: string;
  status: string;
  contentDelta: string;
  contentSnapshot: string;
  thinkingDelta: string;
  thinkingSnapshot: string;
  agentName: string;
  toolOutput: string;
  approvalState: string;
  changedFiles: string[];
  questions: DesktopQuestionPrompt[];
  answers: DesktopQuestionAnswer[];
  title: string;
}

export type DesktopSessionEventKind = 'turnStarted' | 'commandCompleted' | 'toolApprovalRequired' | 'userInputRequired' | 'toolCompleted' | 'toolBlocked' | 'toolFailed' | 'toolApproved' | 'userInputReceived' | 'assistantPreparingContext' | 'assistantGenerating' | 'assistantStreaming' | 'assistantCompleted' | 'turnInterrupted' | 'turnReattached' | 'turnCancelled' | 'turnCompleted' | 'sessionTitleUpdated';

export interface DesktopSessionTurnResult {
  session: SessionPreview;
  assistantSummary: string;
  createdNewSession: boolean;
  toolExecution: NativeToolExecutionResult;
  resolvedCommand: ResolvedCommand | null;
}

export interface DesktopStateChangedEvent {
  currentMode: DesktopMode;
  currentLocale: string;
  timestampUtc: string;
}

export interface DirectConnectServerState {
  enabled: boolean;
  listening: boolean;
  baseUrl: string;
  accessToken: string;
  error: string;
}

export interface DirectConnectSessionEventBatch {
  directConnectSessionId: string;
  latestSequence: number;
  events: DirectConnectSessionEventRecord[];
}

export interface DirectConnectSessionEventRecord {
  sequence: number;
  event: DesktopSessionEvent;
}

export interface DirectConnectSessionState {
  directConnectSessionId: string;
  boundSessionId: string;
  workingDirectory: string;
  status: string;
  createdAtUtc: string;
  lastActivityAtUtc: string;
  latestEventSequence: number;
}

export interface DisconnectAuthRequest {
  scope: string;
  clearPersistedCredentials: boolean;
}

export interface DismissDirectConnectSessionTurnRequest {
  directConnectSessionId: string;
  turn: DismissInterruptedTurnRequest;
}

export interface DismissInterruptedTurnRequest {
  sessionId: string;
}

export interface DismissInterruptedTurnResult {
  sessionId: string;
  dismissed: boolean;
  message: string;
  timestampUtc: string;
}

export interface ExecuteNativeToolRequest {
  toolName: string;
  argumentsJson: string;
  approveExecution: boolean;
}

export interface ExtensionConsentSnapshot {
  name: string;
  installType: string;
  source: string;
  summary: string;
  warnings: string[];
  commands: string[];
  skills: string[];
  agents: string[];
  mcpServers: string[];
  channels: string[];
  contextFiles: string[];
}

export interface ExtensionDefinition {
  name: string;
  version: string;
  path: string;
  wrapperPath: string;
  status: string;
  installType: string;
  source: string;
  userEnabled: boolean;
  workspaceEnabled: boolean;
  isActive: boolean;
  description: string;
  contextFiles: string[];
  commands: string[];
  skills: string[];
  agents: string[];
  mcpServers: string[];
  channels: string[];
  settingsCount: number;
  hookEventCount: number;
  lastError: string;
}

export interface ExtensionScaffoldSnapshot {
  name: string;
  path: string;
  template: string;
  createdManifest: boolean;
  createdFiles: string[];
}

export interface ExtensionSettingsSnapshot {
  extensionName: string;
  version: string;
  installType: string;
  path: string;
  settings: ExtensionSettingValue[];
}

export interface ExtensionSettingValue {
  name: string;
  description: string;
  environmentVariable: string;
  sensitive: boolean;
  userValue: string;
  workspaceValue: string;
  effectiveValue: string;
  hasUserValue: boolean;
  hasWorkspaceValue: boolean;
}

export interface ExtensionSnapshot {
  totalCount: number;
  activeCount: number;
  linkedCount: number;
  missingCount: number;
  extensions: ExtensionDefinition[];
}

export interface FileDiscoverySnapshot {
  gitAware: boolean;
  hasQwenIgnore: boolean;
  candidateFileCount: number;
  visibleFileCount: number;
  gitIgnoredCount: number;
  qwenIgnoredCount: number;
  qwenIgnorePatternCount: number;
  contextFiles: string[];
  sampleVisibleFiles: string[];
  sampleGitIgnoredFiles: string[];
  sampleQwenIgnoredFiles: string[];
}

export interface FollowupSuggestion {
  text: string;
  kind: string;
  source: string;
  confidence: number;
}

export interface FollowupSuggestionSnapshot {
  sessionId: string;
  suppressedReason: string;
  generatedAtUtc: string;
  isSpeculative: boolean;
  cacheStatus: string;
  fingerprint: string;
  suggestions: FollowupSuggestion[];
}

export interface GetChannelPairingRequest {
  name: string;
}

export interface GetDesktopSessionRequest {
  sessionId: string;
  offset: number | null;
  limit: number | null;
}

export interface GetDirectConnectSessionRequest {
  directConnectSessionId: string;
}

export interface GetExtensionSettingsRequest {
  name: string;
}

export interface GetFollowupSuggestionsRequest {
  sessionId: string;
  maxCount: number;
  speculative: boolean;
}

export interface GetMcpResourceRegistryRequest {
  serverName: string;
  forceRefresh: boolean;
}

export interface GetPromptRegistryRequest {
  serverName: string;
  forceRefresh: boolean;
}

export interface GitCheckpointSnapshot {
  commitHash: string;
  message: string;
  createdAt: string;
}

export interface GitHistorySnapshot {
  isInitialized: boolean;
  historyDirectory: string;
  checkpointCount: number;
  currentCheckpoint: string;
  recentCheckpoints: GitCheckpointSnapshot[];
}

export interface GitRepositorySnapshot {
  isGitAvailable: boolean;
  isRepository: boolean;
  worktreeSupported: boolean;
  repositoryRoot: string;
  currentBranch: string;
  currentCommit: string;
  gitVersion: string;
  managedSessionCount: number;
  managedWorktreesRoot: string;
  worktrees: GitWorktreeEntry[];
  history: GitHistorySnapshot;
}

export interface GitWorktreeEntry {
  path: string;
  branch: string;
  head: string;
  name: string;
  sessionId: string;
  isCurrent: boolean;
  isManaged: boolean;
}

export interface InstallExtensionRequest {
  sourcePath: string;
  installMode: string;
  sourceType: string;
  ref: string;
  autoUpdate: boolean;
  allowPreRelease: boolean;
  registryUrl: string;
}

export interface InvokePromptRegistryEntryRequest {
  name: string;
  argumentsJson: string;
}

export interface LocaleOption {
  code: string;
  name: string;
  nativeName: string;
}

export interface McpPromptInvocationResult {
  serverName: string;
  promptName: string;
  output: string;
}

export interface McpResourceReadResult {
  serverName: string;
  uri: string;
  output: string;
}

export interface McpResourceRegistryEntry {
  name: string;
  uri: string;
  qualifiedName: string;
  serverName: string;
  description: string;
  mimeType: string;
  source: string;
}

export interface McpResourceRegistrySnapshot {
  totalCount: number;
  serverCount: number;
  resources: McpResourceRegistryEntry[];
}

export interface McpServerDefinition {
  name: string;
  scope: string;
  transport: string;
  commandOrUrl: string;
  arguments: string[];
  environmentVariables: Record<string, string>;
  headers: Record<string, string>;
  timeoutMs: number | null;
  trust: boolean;
  description: string;
  instructions: string;
  includeTools: string[];
  excludeTools: string[];
  settingsPath: string;
  status: string;
  lastReconnectAttemptUtc: string | null;
  lastError: string;
  hasPersistedToken: boolean;
  hasStaticAuthorizationHeader: boolean;
  authenticationStatus: string;
  discoveredToolsCount: number;
  discoveredPromptsCount: number;
  discoveredResourcesCount: number;
  supportsPrompts: boolean;
  supportsResources: boolean;
  lastDiscoveryUtc: string | null;
}

export interface McpServerRegistrationRequest {
  name: string;
  scope: string;
  transport: string;
  commandOrUrl: string;
  arguments: string[];
  environmentVariables: Record<string, string>;
  headers: Record<string, string>;
  timeoutMs: number | null;
  trust: boolean;
  description: string;
  instructions: string;
  includeTools: string[];
  excludeTools: string[];
}

export interface McpSnapshot {
  totalCount: number;
  connectedCount: number;
  disconnectedCount: number;
  missingCount: number;
  tokenCount: number;
  servers: McpServerDefinition[];
}

export interface NativeToolExecutionResult {
  toolName: string;
  status: string;
  approvalState: string;
  workingDirectory: string;
  output: string;
  errorMessage: string;
  exitCode: number;
  changedFiles: string[];
  questions: DesktopQuestionPrompt[];
  answers: DesktopQuestionAnswer[];
}

export interface NativeToolHostSnapshot {
  registeredCount: number;
  implementedCount: number;
  readyCount: number;
  approvalRequiredCount: number;
  tools: NativeToolRegistration[];
}

export interface NativeToolRegistration {
  name: string;
  displayName: string;
  kind: string;
  isImplemented: boolean;
  approvalState: string;
  approvalReason: string;
}

export interface ProjectSummarySnapshot {
  hasHistory: boolean;
  filePath: string;
  content: string;
  timestampText: string;
  timeAgo: string;
  overallGoal: string;
  currentPlan: string;
  totalTasks: number;
  doneCount: number;
  inProgressCount: number;
  todoCount: number;
  pendingTasks: string[];
  timestampUtc: string;
}

export interface PromptRegistryEntry {
  name: string;
  promptName: string;
  qualifiedName: string;
  serverName: string;
  description: string;
  argumentsJson: string;
  source: string;
}

export interface PromptRegistrySnapshot {
  totalCount: number;
  serverCount: number;
  prompts: PromptRegistryEntry[];
}

export interface QwenCommandSurface {
  id: string;
  name: string;
  scope: string;
  path: string;
  description: string;
  group: string;
}

export interface QwenCompatibilityLayer {
  id: string;
  title: string;
  scope: string;
  priority: number;
  path: string;
  exists: boolean;
  categories: string[];
}

export interface QwenCompatibilitySnapshot {
  projectRoot: string;
  defaultContextFileName: string;
  settingsLayers: QwenCompatibilityLayer[];
  surfaceDirectories: QwenSurfaceDirectory[];
  commands: QwenCommandSurface[];
  skills: QwenSkillSurface[];
}

export interface QwenOAuthDeviceFlowSnapshot {
  flowId: string;
  scope: string;
  status: string;
  verificationUri: string;
  verificationUriComplete: string;
  userCode: string;
  pollIntervalMs: number;
  browserLaunchAttempted: boolean;
  browserLaunchSucceeded: boolean;
  startedAtUtc: string;
  expiresAtUtc: string;
  completedAtUtc: string | null;
  errorMessage: string;
}

export interface QwenRuntimeProfile {
  projectRoot: string;
  globalQwenDirectory: string;
  runtimeBaseDirectory: string;
  runtimeSource: string;
  projectDataDirectory: string;
  chatsDirectory: string;
  historyDirectory: string;
  contextFileNames: string[];
  contextFilePaths: string[];
  modelName: string;
  embeddingModel: string;
  currentLocale: string;
  currentLanguage: string;
  chatCompression: RuntimeChatCompressionSettings | null;
  telemetry: RuntimeTelemetrySettings | null;
  checkpointing: boolean;
  folderTrustEnabled: boolean;
  isWorkspaceTrusted: boolean;
  workspaceTrustSource: string;
  approvalProfile: ApprovalProfile;
}

export interface QwenSkillSurface {
  id: string;
  name: string;
  scope: string;
  path: string;
  description: string;
  allowedTools: string[];
}

export interface QwenSurfaceDirectory {
  id: string;
  title: string;
  path: string;
  exists: boolean;
  itemCount: number;
  summary: string;
}

export interface ReadDirectConnectSessionEventsRequest {
  directConnectSessionId: string;
  afterSequence: number;
  maxCount: number;
}

export interface ReadMcpResourceRegistryEntryRequest {
  name: string;
}

export interface ReconnectMcpServerRequest {
  name: string;
}

export interface RecoverableTurnState {
  sessionId: string;
  prompt: string;
  workingDirectory: string;
  gitBranch: string;
  recoveryReason: string;
  lastUpdatedAtUtc: string;
  contentSnapshot: string;
  toolName: string;
}

export interface RemoveDesktopSessionRequest {
  sessionId: string;
}

export interface RemoveDesktopSessionResult {
  removed: boolean;
  sessionId: string;
  recentSessions: SessionPreview[];
}

export interface RenameDesktopSessionRequest {
  sessionId: string;
  title: string;
}

export interface RenameDesktopSessionResult {
  renamed: boolean;
  sessionId: string;
  title: string;
  recentSessions: SessionPreview[];
}

export interface RemoveExtensionRequest {
  name: string;
}

export interface RemoveMcpServerRequest {
  name: string;
  scope: string;
}

export interface ResearchTrack {
  title: string;
  summary: string;
}

export interface ResolvedCommand {
  name: string;
  scope: string;
  sourcePath: string;
  description: string;
  arguments: string;
  resolvedPrompt: string;
}

export interface RestoreGitCheckpointRequest {
  commitHash: string;
}

export interface ResumeDirectConnectSessionTurnRequest {
  directConnectSessionId: string;
  turn: ResumeInterruptedTurnRequest;
}

export interface ResumeInterruptedTurnRequest {
  sessionId: string;
  recoveryNote: string;
}

export interface RuntimeChatCompressionSettings {
  contextPercentageThreshold: number | null;
}

export interface RuntimeModelCapabilities {
  supportsToolCalls: boolean;
  supportsJsonOutput: boolean;
  supportsStreaming: boolean;
  supportsReasoning: boolean;
  supportsEmbeddings: boolean;
  contextWindowTokens: number | null;
  maxOutputTokens: number | null;
}

export interface RuntimeModelSnapshot {
  defaultModelId: string;
  embeddingModelId: string;
  selectedAuthType: string;
  availableModels: AvailableModel[];
}

export interface RuntimeTelemetrySettings {
  enabled: boolean;
  target: string;
  otlpEndpoint: string;
  otlpProtocol: string;
  logPrompts: boolean;
  outfile: string;
  useCollector: boolean;
}

export interface SelectProjectDirectoryResult {
  cancelled: boolean;
  selectedPath: string;
}

export interface SessionPreview {
  sessionId: string;
  title: string | null;
  lastActivity: string;
  startedAt: string;
  lastUpdatedAt: string;
  category: string;
  mode: DesktopMode;
  status: string;
  workingDirectory: string;
  gitBranch: string;
  messageCount: number;
  transcriptPath: string;
  metadataPath: string;
}

export interface SetExtensionEnabledRequest {
  name: string;
  scope: string;
  enabled: boolean;
}

export interface SetExtensionSettingValueRequest {
  name: string;
  setting: string;
  scope: string;
  value: string;
}

export interface SetLocaleRequest {
  locale: string;
}

export interface StartDesktopSessionTurnRequest {
  sessionId: string;
  prompt: string;
  workingDirectory: string;
  surfaceContext: string;
  toolName: string;
  toolArgumentsJson: string;
  approveToolExecution: boolean;
}

export interface StartDirectConnectSessionTurnRequest {
  directConnectSessionId: string;
  turn: StartDesktopSessionTurnRequest;
}

export interface StartQwenOAuthDeviceFlowRequest {
  scope: string;
}

export interface ToolCatalogSnapshot {
  sourceMode: string;
  totalCount: number;
  allowedCount: number;
  askCount: number;
  denyCount: number;
  tools: ToolDescriptor[];
}

export interface ToolDescriptor {
  name: string;
  displayName: string;
  kind: string;
  sourcePath: string;
  approvalState: string;
  approvalReason: string;
}

export interface UpdateExtensionRequest {
  name: string;
  updateAll: boolean;
}

export interface WorkspaceSnapshot {
  git: GitRepositorySnapshot;
  discovery: FileDiscoverySnapshot;
}

export interface QwenDesktopBridge {
  bootstrap(): Promise<AppBootstrapPayload>;
  setLocale(request: SetLocaleRequest): Promise<DesktopStateChangedEvent>;
  subscribeStateChanged(callback: (payload: DesktopStateChangedEvent) => void): () => void;
  cancelArenaSession(request: CancelArenaSessionRequest): Promise<CancelArenaSessionResult>;
  subscribeArenaEvents(callback: (payload: ArenaSessionEvent) => void): () => void;
  getActiveArenaSessions(): Promise<ActiveArenaSessionState[]>;
  cancelQwenOAuthDeviceFlow(request: CancelQwenOAuthDeviceFlowRequest): Promise<AuthStatusSnapshot>;
  subscribeAuthChanged(callback: (payload: AuthStatusSnapshot) => void): () => void;
  configureCodingPlanAuth(request: ConfigureCodingPlanAuthRequest): Promise<AuthStatusSnapshot>;
  configureOpenAiCompatibleAuth(request: ConfigureOpenAiCompatibleAuthRequest): Promise<AuthStatusSnapshot>;
  configureQwenOAuth(request: ConfigureQwenOAuthRequest): Promise<AuthStatusSnapshot>;
  disconnectAuth(request: DisconnectAuthRequest): Promise<AuthStatusSnapshot>;
  startQwenOAuthDeviceFlow(request: StartQwenOAuthDeviceFlowRequest): Promise<AuthStatusSnapshot>;
  getAuthStatus(): Promise<AuthStatusSnapshot>;
  approveChannelPairing(request: ApproveChannelPairingRequest): Promise<ChannelPairingSnapshot>;
  getChannelPairings(request: GetChannelPairingRequest): Promise<ChannelPairingSnapshot>;
  answerDirectConnectSessionQuestion(request: AnswerDirectConnectSessionQuestionRequest): Promise<DesktopSessionTurnResult>;
  approveDirectConnectSessionTool(request: ApproveDirectConnectSessionToolRequest): Promise<DesktopSessionTurnResult>;
  cancelDirectConnectSessionTurn(request: CancelDirectConnectSessionTurnRequest): Promise<CancelDesktopSessionTurnResult>;
  closeDirectConnectSession(request: CloseDirectConnectSessionRequest): Promise<DirectConnectSessionState>;
  createDirectConnectSession(request: CreateDirectConnectSessionRequest): Promise<DirectConnectSessionState>;
  dismissDirectConnectSessionTurn(request: DismissDirectConnectSessionTurnRequest): Promise<DismissInterruptedTurnResult>;
  getDirectConnectServer(): Promise<DirectConnectServerState>;
  getDirectConnectSession(request: GetDirectConnectSessionRequest): Promise<DirectConnectSessionState>;
  listDirectConnectSessions(): Promise<DirectConnectSessionState[]>;
  readDirectConnectSessionEvents(request: ReadDirectConnectSessionEventsRequest): Promise<DirectConnectSessionEventBatch>;
  resumeDirectConnectSessionTurn(request: ResumeDirectConnectSessionTurnRequest): Promise<DesktopSessionTurnResult>;
  startDirectConnectSessionTurn(request: StartDirectConnectSessionTurnRequest): Promise<DesktopSessionTurnResult>;
  createExtensionScaffold(request: CreateExtensionScaffoldRequest): Promise<ExtensionScaffoldSnapshot>;
  getExtensionSettings(request: GetExtensionSettingsRequest): Promise<ExtensionSettingsSnapshot>;
  installExtension(request: InstallExtensionRequest): Promise<ExtensionSnapshot>;
  previewExtensionConsent(request: InstallExtensionRequest): Promise<ExtensionConsentSnapshot>;
  removeExtension(request: RemoveExtensionRequest): Promise<ExtensionSnapshot>;
  setExtensionEnabled(request: SetExtensionEnabledRequest): Promise<ExtensionSnapshot>;
  setExtensionSetting(request: SetExtensionSettingValueRequest): Promise<ExtensionSettingsSnapshot>;
  updateExtension(request: UpdateExtensionRequest): Promise<ExtensionSnapshot>;
  getFollowupSuggestions(request: GetFollowupSuggestionsRequest): Promise<FollowupSuggestionSnapshot>;
  getMcpResourceRegistry(request: GetMcpResourceRegistryRequest): Promise<McpResourceRegistrySnapshot>;
  readRegisteredMcpResource(request: ReadMcpResourceRegistryEntryRequest): Promise<McpResourceReadResult>;
  addMcpServer(request: McpServerRegistrationRequest): Promise<McpSnapshot>;
  reconnectMcpServer(request: ReconnectMcpServerRequest): Promise<McpSnapshot>;
  removeMcpServer(request: RemoveMcpServerRequest): Promise<McpSnapshot>;
  getPromptRegistry(request: GetPromptRegistryRequest): Promise<PromptRegistrySnapshot>;
  invokeRegisteredPrompt(request: InvokePromptRegistryEntryRequest): Promise<McpPromptInvocationResult>;
  answerPendingQuestion(request: AnswerDesktopSessionQuestionRequest): Promise<DesktopSessionTurnResult>;
  approvePendingTool(request: ApproveDesktopSessionToolRequest): Promise<DesktopSessionTurnResult>;
  cancelSessionTurn(request: CancelDesktopSessionTurnRequest): Promise<CancelDesktopSessionTurnResult>;
  dismissInterruptedTurn(request: DismissInterruptedTurnRequest): Promise<DismissInterruptedTurnResult>;
  subscribeSessionEvents(callback: (payload: DesktopSessionEvent) => void): () => void;
  getSession(request: GetDesktopSessionRequest): Promise<DesktopSessionDetail>;
  getActiveTurns(): Promise<ActiveTurnState[]>;
  removeSession(request: RemoveDesktopSessionRequest): Promise<RemoveDesktopSessionResult>;
  renameSession(request: RenameDesktopSessionRequest): Promise<RenameDesktopSessionResult>;
  resumeInterruptedTurn(request: ResumeInterruptedTurnRequest): Promise<DesktopSessionTurnResult>;
  startSessionTurn(request: StartDesktopSessionTurnRequest): Promise<DesktopSessionTurnResult>;
  executeNativeTool(request: ExecuteNativeToolRequest): Promise<NativeToolExecutionResult>;
  cleanupManagedSession(request: CleanupManagedWorktreeSessionRequest): Promise<WorkspaceSnapshot>;
  createGitCheckpoint(request: CreateGitCheckpointRequest): Promise<WorkspaceSnapshot>;
  createManagedWorktree(request: CreateManagedWorktreeRequest): Promise<WorkspaceSnapshot>;
  getWorkspaceSnapshot(): Promise<WorkspaceSnapshot>;
  restoreGitCheckpoint(request: RestoreGitCheckpointRequest): Promise<WorkspaceSnapshot>;
  selectProjectDirectory(): Promise<SelectProjectDirectoryResult>;
}

export const qwenDesktopChannels = {
  bootstrap: 'qwen-desktop:app:bootstrap',
  setLocale: 'qwen-desktop:app:set-locale',
  subscribeStateChanged: 'qwen-desktop:app:state-changed',
  cancelArenaSession: 'qwen-desktop:arena:cancel',
  subscribeArenaEvents: 'qwen-desktop:arena:event',
  getActiveArenaSessions: 'qwen-desktop:arena:get-active-sessions',
  cancelQwenOAuthDeviceFlow: 'qwen-desktop:auth:cancel-qwen-oauth-device-flow',
  subscribeAuthChanged: 'qwen-desktop:auth:changed',
  configureCodingPlanAuth: 'qwen-desktop:auth:configure-coding-plan',
  configureOpenAiCompatibleAuth: 'qwen-desktop:auth:configure-openai-compatible',
  configureQwenOAuth: 'qwen-desktop:auth:configure-qwen-oauth',
  disconnectAuth: 'qwen-desktop:auth:disconnect',
  startQwenOAuthDeviceFlow: 'qwen-desktop:auth:start-qwen-oauth-device-flow',
  getAuthStatus: 'qwen-desktop:auth:status',
  approveChannelPairing: 'qwen-desktop:channels:approve-pairing',
  getChannelPairings: 'qwen-desktop:channels:get-pairings',
  answerDirectConnectSessionQuestion: 'qwen-desktop:direct-connect:answer-question',
  approveDirectConnectSessionTool: 'qwen-desktop:direct-connect:approve-tool',
  cancelDirectConnectSessionTurn: 'qwen-desktop:direct-connect:cancel-turn',
  closeDirectConnectSession: 'qwen-desktop:direct-connect:close-session',
  createDirectConnectSession: 'qwen-desktop:direct-connect:create-session',
  dismissDirectConnectSessionTurn: 'qwen-desktop:direct-connect:dismiss-interrupted',
  getDirectConnectServer: 'qwen-desktop:direct-connect:get-server',
  getDirectConnectSession: 'qwen-desktop:direct-connect:get-session',
  listDirectConnectSessions: 'qwen-desktop:direct-connect:list-sessions',
  readDirectConnectSessionEvents: 'qwen-desktop:direct-connect:read-events',
  resumeDirectConnectSessionTurn: 'qwen-desktop:direct-connect:resume-interrupted',
  startDirectConnectSessionTurn: 'qwen-desktop:direct-connect:start-turn',
  createExtensionScaffold: 'qwen-desktop:extensions:create-scaffold',
  getExtensionSettings: 'qwen-desktop:extensions:get-settings',
  installExtension: 'qwen-desktop:extensions:install',
  previewExtensionConsent: 'qwen-desktop:extensions:preview-consent',
  removeExtension: 'qwen-desktop:extensions:remove',
  setExtensionEnabled: 'qwen-desktop:extensions:set-enabled',
  setExtensionSetting: 'qwen-desktop:extensions:set-setting',
  updateExtension: 'qwen-desktop:extensions:update',
  getFollowupSuggestions: 'qwen-desktop:followup:get-suggestions',
  getMcpResourceRegistry: 'qwen-desktop:mcp-resources:get-registry',
  readRegisteredMcpResource: 'qwen-desktop:mcp-resources:read',
  addMcpServer: 'qwen-desktop:mcp:add',
  reconnectMcpServer: 'qwen-desktop:mcp:reconnect',
  removeMcpServer: 'qwen-desktop:mcp:remove',
  getPromptRegistry: 'qwen-desktop:prompts:get-registry',
  invokeRegisteredPrompt: 'qwen-desktop:prompts:invoke',
  answerPendingQuestion: 'qwen-desktop:sessions:answer-question',
  approvePendingTool: 'qwen-desktop:sessions:approve-tool',
  cancelSessionTurn: 'qwen-desktop:sessions:cancel-turn',
  dismissInterruptedTurn: 'qwen-desktop:sessions:dismiss-interrupted',
  subscribeSessionEvents: 'qwen-desktop:sessions:event',
  getSession: 'qwen-desktop:sessions:get',
  getActiveTurns: 'qwen-desktop:sessions:get-active-turns',
  removeSession: 'qwen-desktop:sessions:remove',
  renameSession: 'qwen-desktop:sessions:rename',
  resumeInterruptedTurn: 'qwen-desktop:sessions:resume-interrupted',
  startSessionTurn: 'qwen-desktop:sessions:start-turn',
  executeNativeTool: 'qwen-desktop:tools:execute-native',
  cleanupManagedSession: 'qwen-desktop:workspace:cleanup-managed-session',
  createGitCheckpoint: 'qwen-desktop:workspace:create-git-checkpoint',
  createManagedWorktree: 'qwen-desktop:workspace:create-managed-worktree',
  getWorkspaceSnapshot: 'qwen-desktop:workspace:get',
  restoreGitCheckpoint: 'qwen-desktop:workspace:restore-git-checkpoint',
  selectProjectDirectory: 'qwen-desktop:workspace:select-project-directory',
} as const
